#!/bin/bash

echo "Chat UI Manual Test Checklist:"
echo ""
echo "✓ Open zebi.app in browser"
echo "✓ Click floating chat button (bottom right)"
echo "✓ Chat panel slides in from right"
echo "✓ Click a suggestion prompt"
echo "✓ Input populates"
echo "✓ Press Enter to send"
echo "✓ User message appears (blue bubble, right)"
echo "✓ Loading indicator shows"
echo "✓ AI response appears (gray bubble, left)"
echo "✓ Metadata shows (tokens, cost)"
echo "✓ Send follow-up message"
echo "✓ Context maintained"
echo "✓ Click 'Clear conversation'"
echo "✓ Messages cleared"
echo "✓ Click 'X' to close"
echo "✓ Chat panel closes"
echo "✓ Floating button reappears"
echo ""
echo "Test on mobile (responsive design):"
echo "✓ Chat takes full width on mobile"
echo "✓ Input keyboard doesn't cover messages"
echo ""
